### PR TITLE
Fix support for Java 16

### LINKED ISSUE #1112: Illegal reflective access operation
After starting the server, the first user joining the game generates this warning:

[07.03 16:42:36] [Server] [INFO] UUID of player _Hap_ is 85f0078c-fc47-4c25-8c88-2d547a3c64b6
[07.03 16:42:36] [Server] [INFO] _Hap_ joined the game
[07.03 16:42:36] [Server] WARNINGAn illegal reflective access operation has occurred
[07.03 16:42:36] [Server] WARNINGIllegal reflective access by com.comphenix.protocol.reflect.compiler.StructureCompiler (file:/plugins/ProtocolLib%204.6.1%20%23498.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
[07.03 16:42:36] [Server] WARNINGPlease consider reporting this to the maintainers of com.comphenix.protocol.reflect.compiler.StructureCompiler
[07.03 16:42:36] [Server] WARNINGUse --illegal-access=warn to enable warnings of further illegal reflective access operations
[07.03 16:42:36] [Server] WARNINGAll illegal access operations will be denied in a future release

Each login after that does not produce the warning.

Protocol dump: https://pastebin.com/qZ1Ze8WL

### LINKED ISSUE #1122: java 16 error and player kicks (maybe from same isusue?)
**Describe the bug**
Java 16 error and player kicks (maybe from same isusue?)

**To Reproduce**
On server start and join:
https://bin.birdflop.com/tegofojeqa.sql

**Version Info**
ProtocolLib 4.6.0 and also Dev build 498

### LINKED ISSUE #1125: Help
Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @428713ad
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
  	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
  	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
  	at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    com.comphenix.protocol.reflect.StructureModifier@b9437a5[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayOutBlockChange
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[private net.minecraft.server.v1_16_R3.BlockPosition net.minecraft.server.v1_16_R3.PacketPlayOutBlockChange.a, public net.minecraft.server.v1_16_R3.IBlockData net.minecraft.server.v1_16_R3.PacketPlayOutBlockChange.block]
      defaultFields={private net.minecraft.server.v1_16_R3.BlockPosition net.minecraft.server.v1_16_R3.PacketPlayOutBlockChange.a=0}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@4b3a4b1c[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@262544e2
        packetListeners=[PacketAdapter[plugin=AAC5, sending=ListeningWhitelist[priority=LOW, packets=[TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], POSITION[class=PacketPlayOutPosition, id=52], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70], ENTITY_ACTION[class=PacketPlayInEntityAction, id=28], ABILITIES[class=PacketPlayInAbilities, id=26], BLOCK_CHANGE[class=PacketPlayOutBlockChange, id=11], BLOCK_DIG[class=PacketPlayInBlockDig, id=27], LOOK[class=PacketPlayInLook, id=20], FLYING[class=PacketPlayInFlying, id=21], MAP_CHUNK[class=PacketPlayOutMapChunk, id=32], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=22], POSITION[class=PacketPlayInPosition, id=18], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], USE_ENTITY[class=PacketPlayInUseEntity, id=14], USE_ITEM[class=PacketPlayInUseItem, id=46], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], MULTI_BLOCK_CHANGE[class=PacketPlayOutMultiBlockChange, id=59]], gamephase=PLAYING, options=[ASYNC]], receiving=ListeningWhitelist[priority=LOW, packets=[TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], POSITION[class=PacketPlayOutPosition, id=52], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70], ENTITY_ACTION[class=PacketPlayInEntityAction, id=28], ABILITIES[class=PacketPlayInAbilities, id=26], BLOCK_CHANGE[class=PacketPlayOutBlockChange, id=11], BLOCK_DIG[class=PacketPlayInBlockDig, id=27], LOOK[class=PacketPlayInLook, id=20], FLYING[class=PacketPlayInFlying, id=21], MAP_CHUNK[class=PacketPlayOutMapChunk, id=32], VEHICLE_MOVE[class=PacketPlayInVehicleMove, id=22], POSITION[class=PacketPlayInPosition, id=18], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44], USE_ENTITY[class=PacketPlayInUseEntity, id=14], USE_ITEM[class=PacketPlayInUseItem, id=46], BLOCK_PLACE[class=PacketPlayInBlockPlace, id=47], MULTI_BLOCK_CHANGE[class=PacketPlayOutMultiBlockChange, id=59]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=IllegalStack, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=14]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=QualityArmory, sending=ListeningWhitelist[priority=NORMAL, packets=[ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=71]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=LiteBans, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[CHAT[class=PacketPlayInChat, id=3]], gamephase=PLAYING, options=[ASYNC]]], PacketAdapter[plugin=QualityArmory, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=LiteBans, sending=ListeningWhitelist[priority=NORMAL, packets=[DISCONNECT[class=PacketLoginOutDisconnect, id=0]], gamephase=PLAYING, options=[ASYNC]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=VotingPlugin, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[UPDATE_SIGN[class=PacketPlayInUpdateSign, id=43]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=DamageIndicator, sending=ListeningWhitelist[priority=NORMAL, packets=[COMBAT_EVENT[class=PacketPlayOutCombatEvent, id=49], BED[class=PacketPlayOutLookAt, id=51], ENTITY_VELOCITY[class=PacketPlayOutEntityVelocity, id=70], ANIMATION[class=PacketPlayOutAnimation, id=5], ATTACH_ENTITY[class=PacketPlayOutAttachEntity, id=69], ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], BLOCK_BREAK_ANIMATION[class=PacketPlayOutBlockBreakAnimation, id=8], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], ENTITY_EQUIPMENT[class=PacketPlayOutEntityEquipment, id=71], ENTITY_LOOK[class=PacketPlayOutEntityLook, id=41], UPDATE_ENTITY_NBT[PLAY, SERVER, 253, classNames: [net.minecraft.server.v1_16_R3.PacketPlayOutUpdateEntityNBT] (unregistered)], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], SPAWN_ENTITY_EXPERIENCE_ORB[class=PacketPlayOutSpawnEntityExperienceOrb, id=1], NAMED_ENTITY_SPAWN[class=PacketPlayOutNamedEntitySpawn, id=4], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], SPAWN_ENTITY_PAINTING[class=PacketPlayOutSpawnEntityPainting, id=3], ENTITY_TELEPORT[class=PacketPlayOutEntityTeleport, id=86], COLLECT[class=PacketPlayOutCollect, id=85], REMOVE_ENTITY_EFFECT[class=PacketPlayOutRemoveEntityEffect, id=55], ENTITY_STATUS[class=PacketPlayOutEntityStatus, id=26], ENTITY_HEAD_ROTATION[class=PacketPlayOutEntityHeadRotation, id=58], ENTITY_EFFECT[class=PacketPlayOutEntityEffect, id=89]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@1b39371c
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@313a02c1
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2841cd51
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@244f9eef
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@761cccad
        server=CraftServer{serverName=Purpur,serverVersion=git-Purpur-1038,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@31dc984b
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=1
        phasePlayingCount=9
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@347275b8
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@3bc24447
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@6ac42cc0[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@2a077fc8=[com.comphenix.protocol.injector.StructureCache$1@46e9b70b]}
      listenerLock=java.lang.Object@6191d5db
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@48d855d2
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@331d225
      reporter=com.comphenix.protocol.ProtocolLib$1@761cccad
      unknownPermGenBean=java.lang.Object@86b6ca7
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16
  Server:
    git-Purpur-1038 (MC: 1.16.5)

### LINKED ISSUE #1126: zz
Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @5023d3b0
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
  	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
  	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
  	at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    com.comphenix.protocol.reflect.StructureModifier@7608f30c[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook
      target=<null>
      converter=<null>
      fieldType=float
      data=[public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.yaw, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.pitch]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@36773e65[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@393a3f71
        packetListeners=[PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[KEEP_ALIVE[class=PacketPlayInKeepAlive, id=16]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=LOW, packets=[NAMED_SOUND_EFFECT[class=PacketPlayOutNamedSoundEffect, id=81]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=MONITOR, packets=[EXPLOSION[class=PacketPlayOutExplosion, id=27], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44]], gamephase=PLAYING, options=[]], receiving=ListeningWhitelist[priority=MONITOR, packets=[EXPLOSION[class=PacketPlayOutExplosion, id=27], ARM_ANIMATION[class=PacketPlayInArmAnimation, id=44]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=AuthMe, sending=ListeningWhitelist[priority=NORMAL, packets=[SET_SLOT[class=PacketPlayOutSetSlot, id=21], WINDOW_ITEMS[class=PacketPlayOutWindowItems, id=19]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=NORMAL, packets=[USE_ENTITY[class=PacketPlayInUseEntity, id=14]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=ListeningWhitelist[priority=HIGHEST, packets=[POSITION[class=PacketPlayOutPosition, id=52]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[BLOCK_DIG[class=PacketPlayInBlockDig, id=27]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[TELEPORT_ACCEPT[class=PacketPlayInTeleportAccept, id=0], FLYING[class=PacketPlayInFlying, id=21], LOOK[class=PacketPlayInLook, id=20], POSITION_LOOK[class=PacketPlayInPositionLook, id=19], POSITION[class=PacketPlayInPosition, id=18]], gamephase=PLAYING, options=[]]], PacketAdapter[plugin=NoCheatPlus, sending=EMPTY_WHITELIST, receiving=ListeningWhitelist[priority=LOW, packets=[LOOK[class=PacketPlayInLook, id=20], POSITION_LOOK[class=PacketPlayInPositionLook, id=19]], gamephase=PLAYING, options=[]]]]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@81b2bc9
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@e246612
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@12ff5a5
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@69869346
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.0, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@3812a8dc
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-576,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.0
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@6b5710e7
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=10
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@7e186a7
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@46761c1
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@62af97bb[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@da5d2a3d=[com.comphenix.protocol.injector.StructureCache$1@252d8a4e], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@cd59befd=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@2e72e4f2], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@176fd559=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@1124f194], com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@3da1400=[com.comphenix.protocol.reflect.compiler.BackgroundCompiler$1@fa8be44]}
      listenerLock=java.lang.Object@469e3a05
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@7ff21350
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@49ece56b
      reporter=com.comphenix.protocol.ProtocolLib$1@3812a8dc
      unknownPermGenBean=java.lang.Object@3fc388c
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.0
  Java Version:
    16
  Server:
    git-Paper-576 (MC: 1.16.5)

### LINKED ISSUE #1127: [ERROR]: INTERNAL ERROR: Cannot compile structure. Disabling compiler.
**Error description:**
ProtocolLib cannot compile and show this error when player join the game.

**Version Info:**
- git-Paper-576 (MC: 1.16.5)
- ProtocolLib v4.6.1-SNAPSHOT-b498
- Java SE Developpement Kit 16

**Error in console:**
_[ProtocolLib-StructureCompiler 0/ERROR]:   [ProtocolLib] INTERNAL ERROR: Cannot compile structure. Disabing compiler.
  If this problem hasn't already been reported, please open a ticket
  at https://github.com/dmulloy2/ProtocolLib/issues with the following data:
  Stack Trace:
  java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @f4eb92d
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
  	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
  	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
  	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.generateClass(StructureCompiler.java:299)
  	at com.comphenix.protocol.reflect.compiler.StructureCompiler.compile(StructureCompiler.java:213)
  	at com.comphenix.protocol.reflect.compiler.BackgroundCompiler$2.call(BackgroundCompiler.java:204)
  	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
  	at java.base/java.lang.Thread.run(Thread.java:831)
  Dump:
  Parameters: 
    com.comphenix.protocol.reflect.StructureModifier@3b01ba64[
      targetType=class net.minecraft.server.v1_16_R3.PacketPlayInFlying$PacketPlayInPositionLook
      target=<null>
      converter=<null>
      fieldType=class java.lang.Object
      data=[public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.x, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.y, public double net.minecraft.server.v1_16_R3.PacketPlayInFlying.z, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.yaw, public float net.minecraft.server.v1_16_R3.PacketPlayInFlying.pitch, protected boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.f, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasPos, public boolean net.minecraft.server.v1_16_R3.PacketPlayInFlying.hasLook]
      defaultFields={}
      subtypeCache={}
      customConvertHandling=false
      useStructureCompiler=true
    ]
    manager:
      com.comphenix.protocol.injector.PacketFilterManager@1fdbde47[
        unhookTask=com.comphenix.protocol.injector.DelayedSingleTask@57f57f49
        packetListeners=[com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@331d680, PacketAdapter[plugin=HolographicDisplays, sending=ListeningWhitelist[priority=NORMAL, packets=[REL_ENTITY_MOVE_LOOK[class=PacketPlayOutRelEntityMoveLook, id=40], REL_ENTITY_MOVE[class=PacketPlayOutRelEntityMove, id=39], ENTITY_METADATA[class=PacketPlayOutEntityMetadata, id=68], SPAWN_ENTITY_LIVING[class=PacketPlayOutSpawnEntityLiving, id=2], SPAWN_ENTITY[class=PacketPlayOutSpawnEntity, id=0]], gamephase=PLAYING, options=[]], receiving=EMPTY_WHITELIST], com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketListener@4597c633, com.bergerkiller.bukkit.common.internal.network.ProtocolLibPacketHandler$CommonPacketMonitor@bf7b9b9]
        packetInjector=com.comphenix.protocol.injector.netty.ProtocolInjector$5@20740e21
        playerInjection=com.comphenix.protocol.injector.netty.ProtocolInjector$4@169042d1
        inputBufferedPackets=[]
        recievedListeners=com.comphenix.protocol.injector.SortedPacketListenerList@57f88fa2
        sendingListeners=com.comphenix.protocol.injector.SortedPacketListenerList@2b0bbd23
        hasClosed=false
        classLoader=PluginClassLoader{plugin=ProtocolLib v4.6.1-SNAPSHOT-b498, pluginEnabled=true, url=plugins\ProtocolLib.jar}
        reporter=com.comphenix.protocol.ProtocolLib$1@2b8eab65
        server=CraftServer{serverName=Paper,serverVersion=git-Paper-576,minecraftVersion=1.16.5}
        library=ProtocolLib v4.6.1-SNAPSHOT-b498
        asyncFilterManager=com.comphenix.protocol.async.AsyncFilterManager@2c8aefc1
        knowsServerPackets=true
        knowsClientPackets=true
        phaseLoginCount=0
        phasePlayingCount=6
        packetCreation=false
        nettyInjector=com.comphenix.protocol.injector.netty.ProtocolInjector@274eeeca
        pluginVerifier=com.comphenix.protocol.injector.PluginVerifier@89117e8
        hasRecycleDistance=true
        minecraftVersion=(MC: 1.16.5)
        debug=false
      ]
  Sender:
    com.comphenix.protocol.reflect.compiler.BackgroundCompiler@23ace861[
      listeners={com.comphenix.protocol.reflect.compiler.StructureCompiler$StructureKey@86265f90=[com.comphenix.protocol.injector.StructureCache$1@708d4826]}
      listenerLock=java.lang.Object@2065c043
      compiler=com.comphenix.protocol.reflect.compiler.StructureCompiler@204badf0
      enabled=false
      shuttingDown=false
      executor=java.util.concurrent.Executors$FinalizableDelegatedExecutorService@6460b678
      reporter=com.comphenix.protocol.ProtocolLib$1@2b8eab65
      unknownPermGenBean=java.lang.Object@7eb60eaa
      permGenBean=<null>
      disablePermGenFraction=0.65
    ]
  Version:
    ProtocolLib v4.6.1-SNAPSHOT-b498
  Java Version:
    16
  Server:
    git-Paper-576 (MC: 1.16.5)_

### PR DESCRIPTION
**Pull request by PimvanderLoos**
- Switched from the now-unavailable [ClassLoader::defineClass](https://docs.oracle.com/javase/8/docs/api/java/lang/ClassLoader.html#defineClass-java.lang.String-byte:A-int-int-) method to the [MethodHandles.Lookup::defineClass](https://download.java.net/java/early_access/jdk16/docs/api/java.base/java/lang/invoke/MethodHandles.Lookup.html#defineClass(byte%5B%5D)) instead when running on Java 16.

Closes #1122, Closes #1125, Closes #1126, Closes #1127.

As noted in [JEP396](https://openjdk.java.net/jeps/396#:~:text=The%20primary%20risk%20of%20this%20proposal%20is%20that%20existing%20Java%20code%20will%20fail%20to%20run) (which is part of Java 16):

> The primary risk of this proposal is that existing Java code will fail to run. The kinds of code that will fail include, but are not limited, to:
> * Frameworks that use the protected defineClass methods of java.lang.ClassLoader in order to define new classes in existing class loaders. Such frameworks should instead use java.lang.invoke.MethodHandles.Lookup::defineClass, which has been available since JDK 9.

This PR does just that. When the server runs on Java 16, the new MethodHandles.Invoke::defineClass system will be used.

Note that this new system does not use the provided ClassLoader object anymore (the new method defines the classes in the loader of the caller). However, considering ProtocolLib only uses its own ClassLoader for the StructureCompiler anyway, this should not be a problem other than that it looks a little misleading.

To make sure this worked fine, I used LibsDisguises (6eaa42c) on Minecraft 1.16.5 with Java 15 (to ensure this PR did not accidentally break on older versions) and Java 16. 

EDIT: This PR currently only applies to Java 16+, to make sure to not break on that version. This means that this PR applies to the smallest possible group. However, that also means that this does not get rid of the "Illegal reflective access operation" message. If lower versions were to be included, then this PR would also close #1112. 
The issue is that I don't know exactly when that warning was introduced, and I've been having some difficulties getting Java 9 and 10 to work, so I cannot test it myself. However, the methods used in the PR have been available since Java 9, so it should be fine to use it starting from that version. 
Let me know what you think!

### CODE REVIEW

File: src/main/java/com/comphenix/protocol/reflect/compiler/StructureCompiler.java [hunk 1]
```diff
@@ -289,36 +297,54 @@ private String getCompiledName(StructureModifier<?> source) {
...
+			defineMethod = defined;
+		}
+		return (Class<?>) defineMethod.invoke(loader, null, data, 0, data.length);
+	}
+
+	private Class<?> defineClassModern(byte[] data) throws InvocationTargetException, IllegalAccessException,
+			ClassNotFoundException, NoSuchMethodException {
+		if (defineMethod == null || lookup == null)
+		{
+			Class<?> lookupClass = Class.forName("java.lang.invoke.MethodHandles$Lookup");
```
Comment (dmulloy2) [inline src/main/java/com/comphenix/protocol/reflect/compiler/StructureCompiler.java:324]: Might not be a bad idea to cache these Class#forName calls

**Comment by dmulloy2** [comment]
Looks good for the most part. Might not be a bad idea to cache some of the Class#forName calls. Any particular reason this is still marked as a draft?

File: src/main/java/com/comphenix/protocol/reflect/compiler/StructureCompiler.java (hunk 1 above)
Comment (PimvanderLoos) [reply src/main/java/com/comphenix/protocol/reflect/compiler/StructureCompiler.java]: Yep, definitely. Will add that.

**Comment by PimvanderLoos** [comment]
Thanks for the feedback. I've changed it so that it won't retrieve the classes/methods every time now.

The reason it's marked as a draft is that I'd like to know what your thoughts are regarding the lowest Java version to use this new method on. The new method is currently used on Java 16+.
It is needed on Java 16+, as the old method no longer works, but on versions before Java 16, you get the illegal access message with the old method (as shown by #1112). However, I don't know when Java started throwing this message. The new method should work on Java 9+ (all classes/methods exist), but I cannot test that (installing J9 and J10 on my system was a nightmare, so I gave up on them). 
The new method worked fine on J11, though (the lowest version I could test it on).

Other than that, I think it's ready.

**Comment by dmulloy2** [comment]
I ended up getting Java 9 to work with this. I'd say lower the version you check against to 53

**Comment by PimvanderLoos** [comment]
All right, I've updated it so that the Lookup method is used on Java 9+. I think this PR is now ready and as such have removed the draft tag.

**Comment by dmulloy2** [comment]
Thank you for your work on this!
