### PR TITLE
Fix & improve PacketContainer serialization & cloning

### LINKED ISSUE #1786: Error while cloning clientbound player chat packets in 1.19.1
- [x] This issue is not solved in a development build

**Describe the bug**
An error occurs when cloning clientbound player chat packets in 1.19.1
**The cloning works fine for the first packet cloned every time the player rejoins the game.**
The error: https://pastebin.com/dumnuW2L

**To Reproduce**
1. Have code that intercepts and deepClones clientbound player chat packets
2. Join the game
3. Do `/say Hello` with your player, this one should work fine
4. Do `/say Hello` again, this one should fail, see console for error

**Expected behavior**
Cloning works

**Version Info**
https://pastebin.com/h266ciKW

### PR DESCRIPTION
**Pull request by derklaro**
### Main Issue & fix

This pull request fixes a bug which causes invalid data to be used when a packet container is deserialized from an object input stream. The previous code would read the amount of bytes written to the stream, then call `ByteBuf#writeBytes(stream, length)` to transfer the bytes into the buffer. That's in general correct. The issue comes from `ObjectInputStream$BlockDataInputStream#read`. When constructing an ObjectInputStream, the original stream is wrapped in that named subclass, which then enables blocking mode. In blocking mode only a fixed size of data can be read until the buffer needs to refill:
```java
if (pos == end) {
  refill();
}

if (end < 0) {
  return -1;
}

int nread = Math.min(len, end - pos); // len is our input
System.arraycopy(buf, pos, b, off, nread);
pos += nread;
return nread;
```
In my tests the stream was readin a maximum of 1024 bytes before stopping and refilling (the maximum block size). I fixed that isasue by using the output of `ByteBuf#writeBytes` (which returns the number of bytes written) and recall the write method until the amount of expected bytes were written or the input stream is exhausted (the exhausted check is just to prevent an infinite loop, in general that should not happen).

I added a test which verifies that serialization with a big packet works as expected.

### Other changes
1. I also changed how deep cloning with serialization works. Rather than allocating multiple memory segments (one for the serialization byte array input stream, one ByteBuf for serialization, one ByteBuf for deserialization), I moved the cloning code in a way that it only uses one ByteBuf, serializes the packet into it and reads the packet from it again.
2. All ByteBufs which we are allocating during that process are now released as well. It doesn't matter *that* much for heap buffers, but as `Unpooled#buffer` (as well as the old `PooledByteBufAllocator.DEFAULT.allocate` way) might also allocate direct buffers we need to be careful to not accidentally leak native memory (which we did previously). I used `ReferenceCountUtil.safeRelease` for that purpose as it prevents throwing uncaught exceptions during the release process.
3. I deprecated `PacketContainer#createPacketBuffer` in favor of `MinecraftReflection#createPacketDataSerializer(int)`, that way buffers with a fixed size can be allocated, preventing the need (when deserializing) to resize the buffer. Passing a zero or negative number to the method will allocate a buffer with an initial size of 256 which is the default in netty (but the constant is not exposed).
4. I cached the constructor/method which we use to create packets from buffers which should speed up the process a bit, considering that cloning might be something executed very often.

Thanks to @LOOHP for reporting this issue :)
Closes #1786

### CODE REVIEW

File: src/main/java/com/comphenix/protocol/events/PacketContainer.java [hunk 1]
```diff
@@ -17,17 +17,26 @@
 
 package com.comphenix.protocol.events;
 
+import com.comphenix.protocol.reflect.accessors.Accessors;
```
Comment (dmulloy2) [inline src/main/java/com/comphenix/protocol/events/PacketContainer.java:20]: nit: i would prefer the import order be separated by tld with java first then in alphabetical order

**Review by dmulloy2 — APPROVED** [review]

File: src/main/java/com/comphenix/protocol/events/PacketContainer.java (hunk 1 above)
Comment (derklaro) [reply src/main/java/com/comphenix/protocol/events/PacketContainer.java]: should be done

**Review by dmulloy2 — APPROVED** [review]
